{"name": "Проверка ошибки при попытке получения заказа с несуществующим номером", "status": "passed", "steps": [{"name": "Отправляем запрос GET на получение заказа по его номеру", "status": "passed", "parameters": [{"name": "id_track", "value": "1277187"}], "start": 1717180993349, "stop": 1717180993837}], "start": 1717180993349, "stop": 1717180993841, "uuid": "b6190248-67c0-435e-b709-40bf33ad3c80", "historyId": "fe8fe88595bad690e39b7dff77a74d5a", "testCaseId": "fe8fe88595bad690e39b7dff77a74d5a", "fullName": "tests.test_7_get_order.TestGetOrder#test_get_order_by_invalid_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_7_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-5IEA5R0"}, {"name": "thread", "value": "2896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_7_get_order"}]}